#@server = https://angelloxz-shiny-space-waddle-q7qq69w96vqx3qgp-8080.preview.app.github.dev
@server = https://ec3ang.onrender.com
@apiserver = {{server}}/api/instrumento
###
GET {{server}}/codigo
###
GET {{server}}/nombre-completo
###
GET {{apiserver}}/listar
###
POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=tambor
###
DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=52
